DATA PRE-PROCESSING

In [19]:
import pandas as pd
df=pd.read_csv('/content/drive/MyDrive/basics_data.csv')
df

F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
7    7   8   9   NaN  11.0  12      UK  green  Female
8    8   9  10   NaN  12.0  13     IND  green  Female
9    9  10  11  12.0  13.0  14      UK  green  Female
10  10  11  12  13.0   NaN  15     IND   blue  Female
11  11  12  13  14.0   NaN  16      UK   blue  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female

In [20]:
#Missing Value
df.isna().sum()

F1         0
F2         0
F3         0
F4         2
F5         2
F6         0
Country    0
Color      0
Target     0
dtype: int64

In [21]:
#Method-1 Delete
df1=df.dropna()
df1

F1  F2  F3    F4    F5  F6 Country  Color  Target
0    0   1   2   3.0   4.0   5     IND    red    Male
1    1   2   3   4.0   5.0   6      UK    red    Male
2    2   3   4   5.0   6.0   7     IND    red    Male
3    3   4   5   6.0   7.0   8      UK    red    Male
4    4   5   6   7.0   8.0   9     IND  green    Male
5    5   6   7   8.0   9.0  10      UK  green    Male
6    6   7   8   9.0  10.0  11     IND  green    Male
9    9  10  11  12.0  13.0  14      UK  green  Female
12  12  13  14  15.0  16.0  17     IND   blue  Female
13  13  14  15  16.0  17.0  18      UK   blue  Female

In [22]:
df[['F2','F3']] # F2 & F3 column
df.iloc[:,[2,3]] #col with index

F3    F4
0    2   3.0
1    3   4.0
2    4   5.0
3    5   6.0
4    6   7.0
5    7   8.0
6    8   9.0
7    9   NaN
8   10   NaN
9   11  12.0
10  12  13.0
11  13  14.0
12  14  15.0
13  15  16.0

In [23]:
# Method-2 Imputation
import numpy as np
from sklearn.impute import SimpleImputer
si= SimpleImputer(missing_values=np.nan, strategy='mean') # median, most_frequent
df[['F4','F5']]= si.fit_transform(df[['F4','F5']])
df

F1  F2  F3         F4         F5  F6 Country  Color  Target
0    0   1   2   3.000000   4.000000   5     IND    red    Male
1    1   2   3   4.000000   5.000000   6      UK    red    Male
2    2   3   4   5.000000   6.000000   7     IND    red    Male
3    3   4   5   6.000000   7.000000   8      UK    red    Male
4    4   5   6   7.000000   8.000000   9     IND  green    Male
5    5   6   7   8.000000   9.000000  10      UK  green    Male
6    6   7   8   9.000000  10.000000  11     IND  green    Male
7    7   8   9   9.333333  11.000000  12      UK  green  Female
8    8   9  10   9.333333  12.000000  13     IND  green  Female
9    9  10  11  12.000000  13.000000  14      UK  green  Female
10  10  11  12  13.000000   9.833333  15     IND   blue  Female
11  11  12  13  14.000000   9.833333  16      UK   blue  Female
12  12  13  14  15.000000  16.000000  17     IND   blue  Female
13  13  14  15  16.000000  17.000000  18      UK   blue  Female

In [24]:
# Check Categorical Data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 9 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   F1       14 non-null     int64  
 1   F2       14 non-null     int64  
 2   F3       14 non-null     int64  
 3   F4       14 non-null     float64
 4   F5       14 non-null     float64
 5   F6       14 non-null     int64  
 6   Country  14 non-null     object 
 7   Color    14 non-null     object 
 8   Target   14 non-null     object 
dtypes: float64(2), int64(4), object(3)
memory usage: 1.1+ KB


In [25]:
# Method-1 Label Encoder (Target- Male/Female)
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df['Target']=le.fit_transform(df['Target'])
print(le.classes_)
df

['Female' 'Male']


F1  F2  F3         F4         F5  F6 Country  Color  Target
0    0   1   2   3.000000   4.000000   5     IND    red       1
1    1   2   3   4.000000   5.000000   6      UK    red       1
2    2   3   4   5.000000   6.000000   7     IND    red       1
3    3   4   5   6.000000   7.000000   8      UK    red       1
4    4   5   6   7.000000   8.000000   9     IND  green       1
5    5   6   7   8.000000   9.000000  10      UK  green       1
6    6   7   8   9.000000  10.000000  11     IND  green       1
7    7   8   9   9.333333  11.000000  12      UK  green       0
8    8   9  10   9.333333  12.000000  13     IND  green       0
9    9  10  11  12.000000  13.000000  14      UK  green       0
10  10  11  12  13.000000   9.833333  15     IND   blue       0
11  11  12  13  14.000000   9.833333  16      UK   blue       0
12  12  13  14  15.000000  16.000000  17     IND   blue       0
13  13  14  15  16.000000  17.000000  18      UK   blue       0

In [26]:
# One Hot Encoder
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
df1 = pd.DataFrame(ohe.fit_transform(df[['Color']]).toarray(),
                   columns=['Color_'+str(i) for i in range(len(df['Color'].value_counts()))])
df1
df2 = pd.concat([df,df1], axis=1)
df2
df3=df2.drop(['Color'],axis=1)
df3

F1  F2  F3         F4         F5  F6 Country  Target  Color_0  Color_1  \
0    0   1   2   3.000000   4.000000   5     IND       1      0.0      0.0   
1    1   2   3   4.000000   5.000000   6      UK       1      0.0      0.0   
2    2   3   4   5.000000   6.000000   7     IND       1      0.0      0.0   
3    3   4   5   6.000000   7.000000   8      UK       1      0.0      0.0   
4    4   5   6   7.000000   8.000000   9     IND       1      0.0      1.0   
5    5   6   7   8.000000   9.000000  10      UK       1      0.0      1.0   
6    6   7   8   9.000000  10.000000  11     IND       1      0.0      1.0   
7    7   8   9   9.333333  11.000000  12      UK       0      0.0      1.0   
8    8   9  10   9.333333  12.000000  13     IND       0      0.0      1.0   
9    9  10  11  12.000000  13.000000  14      UK       0      0.0      1.0   
10  10  11  12  13.000000   9.833333  15     IND       0      1.0      0.0   
11  11  12  13  14.000000   9.833333  16      UK       0      1.0      0.0   
12  12  13  14  15.000000  16.000000  17     IND       0      1.0      0.0   
13  13  14  15  16.000000  17.000000  18      UK       0      1.0      0.0   

    Color_2  
0       1.0  
1       1.0  
2       1.0  
3       1.0  
4       0.0  
5       0.0  
6       0.0  
7       0.0  
8       0.0  
9       0.0  
10      0.0  
11      0.0  
12      0.0  
13      0.0

In [27]:
dfc = pd.DataFrame(ohe.fit_transform(df[['Country']]).toarray(),
                   columns=['Country_'+str(i) for i in range(len(df['Country'].value_counts()))])
dfc
df3 = pd.concat([df3,dfc], axis=1)
df3
df4=df3.drop(['Country'], axis=1)
df4


F1  F2  F3         F4         F5  F6  Target  Color_0  Color_1  Color_2  \
0    0   1   2   3.000000   4.000000   5       1      0.0      0.0      1.0   
1    1   2   3   4.000000   5.000000   6       1      0.0      0.0      1.0   
2    2   3   4   5.000000   6.000000   7       1      0.0      0.0      1.0   
3    3   4   5   6.000000   7.000000   8       1      0.0      0.0      1.0   
4    4   5   6   7.000000   8.000000   9       1      0.0      1.0      0.0   
5    5   6   7   8.000000   9.000000  10       1      0.0      1.0      0.0   
6    6   7   8   9.000000  10.000000  11       1      0.0      1.0      0.0   
7    7   8   9   9.333333  11.000000  12       0      0.0      1.0      0.0   
8    8   9  10   9.333333  12.000000  13       0      0.0      1.0      0.0   
9    9  10  11  12.000000  13.000000  14       0      0.0      1.0      0.0   
10  10  11  12  13.000000   9.833333  15       0      1.0      0.0      0.0   
11  11  12  13  14.000000   9.833333  16       0      1.0      0.0      0.0   
12  12  13  14  15.000000  16.000000  17       0      1.0      0.0      0.0   
13  13  14  15  16.000000  17.000000  18       0      1.0      0.0      0.0   

    Country_0  Country_1  
0         1.0        0.0  
1         0.0        1.0  
2         1.0        0.0  
3         0.0        1.0  
4         1.0        0.0  
5         0.0        1.0  
6         1.0        0.0  
7         0.0        1.0  
8         1.0        0.0  
9         0.0        1.0  
10        1.0        0.0  
11        0.0        1.0  
12        1.0        0.0  
13        0.0        1.0

In [28]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   F1         14 non-null     int64  
 1   F2         14 non-null     int64  
 2   F3         14 non-null     int64  
 3   F4         14 non-null     float64
 4   F5         14 non-null     float64
 5   F6         14 non-null     int64  
 6   Target     14 non-null     int64  
 7   Color_0    14 non-null     float64
 8   Color_1    14 non-null     float64
 9   Color_2    14 non-null     float64
 10  Country_0  14 non-null     float64
 11  Country_1  14 non-null     float64
dtypes: float64(7), int64(5)
memory usage: 1.4 KB


In [29]:
# Input and Target Split
y=df4['Target']
x=df4.drop(['Target'],axis=1)
print(x.shape)
print(y.shape)

(14, 11)
(14,)


In [30]:
# Train Test Split
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(11, 11)
(3, 11)
(11,)
(3,)


In [31]:
# Feature Scaling, Standardization
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train_std=sc.fit_transform(x_train)
x_test_std=sc.transform(x_test)
print(x_test_std)

[[-0.86639385 -0.86639385 -0.86639385 -0.83478059 -0.73403606 -0.86639385
  -0.75592895 -0.75592895  1.63299316 -1.09544512  1.09544512]
 [ 0.04125685  0.04125685  0.04125685 -0.07588914  0.25466557  0.04125685
  -0.75592895  1.32287566 -0.61237244 -1.09544512  1.09544512]
 [-0.18565582 -0.18565582 -0.18565582 -0.15177829  0.00749016 -0.18565582
  -0.75592895  1.32287566 -0.61237244  0.91287093 -0.91287093]]


In [32]:
# Normalization
from sklearn.preprocessing import MinMaxScaler
mn=MinMaxScaler()
x_train_norm=mn.fit_transform(x_train)
x_test_norm=mn.transform(x_test)
print(x_test_norm)

[[0.23076923 0.23076923 0.23076923 0.23076923 0.23076923 0.23076923
  0.         0.         1.         0.         1.        ]
 [0.53846154 0.53846154 0.53846154 0.48717949 0.53846154 0.53846154
  0.         1.         0.         0.         1.        ]
 [0.46153846 0.46153846 0.46153846 0.46153846 0.46153846 0.46153846
  0.         1.         0.         1.         0.        ]]


In [34]:
# Feature Extraction
# PCA
from sklearn.decomposition import PCA
pca=PCA(n_components=5) # <= No. of Features
x_train_pca=pca.fit_transform(x_train) # Unsupervised
x_test_pca=pca.transform(x_test)
print(x_test_pca)

[[ 8.98655108 -0.18198704  0.87331454 -0.48997106  0.38640521]
 [-0.54003448 -1.03325553  0.72063851  0.75011664  0.25360375]
 [ 1.64620285 -0.77216225 -0.48809724  0.49886903 -0.58259137]]


In [37]:
#LDA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis as LDA
lda=LDA(n_components=1) # min(1, No. of Class - 1)
x_train_lda=lda.fit_transform(x_train,y_train) # Supervised
x_test_lda=lda.transform(x_test)
print(x_test_lda)

[[ 2.07762371]
 [-0.16556616]
 [ 1.12299755]]
